version: "3.8"
services:
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_namenode_name_dir=/hadoop/dfs/name
      - HDFS_CONF_dfs_replication=3
      - HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check=false
      - MAPRED_CONF_mapreduce_framework_name=yarn
      - YARN_CONF_yarn_resourcemanager_hostname=hadoop-resourcemanager
      - YARN_CONF_yarn_resourcemanager_address=hadoop-resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=hadoop-resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource_tracker_address=hadoop-resourcemanager:8031
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
      - 9000:9000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - hadoop-network

  hadoop-datanode-1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode-1
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_replication=3
      - HDFS_CONF_dfs_datanode_data_dir=/hadoop/dfs/data
      - HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check=false
    volumes:
      - hadoop_datanode_1:/hadoop/dfs/data
    ports:
      - 9864:9864
    depends_on:
      - hadoop-namenode
    networks:
      - hadoop-network

  hadoop-datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode-2
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_replication=3
      - HDFS_CONF_dfs_datanode_data_dir=/hadoop/dfs/data
      - HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check=false
    volumes:
      - hadoop_datanode_2:/hadoop/dfs/data
    ports:
      - 9865:9864
    depends_on:
      - hadoop-namenode
    networks:
      - hadoop-network

  hadoop-datanode-3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode-3
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - HDFS_CONF_dfs_replication=3
      - HDFS_CONF_dfs_datanode_data_dir=/hadoop/dfs/data
      - HDFS_CONF_dfs_namenode_datanode_registration_ip_hostname_check=false
    volumes:
      - hadoop_datanode_3:/hadoop/dfs/data
    ports:
      - 9866:9864
    depends_on:
      - hadoop-namenode
    networks:
      - hadoop-network

  hadoop-resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-resourcemanager
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=hadoop-resourcemanager
    depends_on:
      - hadoop-namenode
    networks:
      - hadoop-network

  hadoop-nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-nodemanager
    environment:
      - CLUSTER_NAME=hadoop
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=hadoop-resourcemanager
    depends_on:
      - hadoop-resourcemanager
    networks:
      - hadoop-network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_HOST=spark-master
    ports:
      - 7077:7077
      - 8080:8080
    networks:
      - hadoop-network
    depends_on:
      - hadoop-namenode
      - hadoop-datanode-1
      - hadoop-datanode-2
      - hadoop-datanode-3

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    networks:
      - hadoop-network

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    networks:
      - hadoop-network

  spark-worker-3:
    image: bitnami/spark:latest
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    depends_on:
      - spark-master
    networks:
      - hadoop-network

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - hadoop-network
    depends_on:
      - spark-master

networks:
  hadoop-network:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode_1:
  hadoop_datanode_2:
  hadoop_datanode_3: